### ISSUE TITLE
New flight model changes to flaps in World Update 3 negatively impacts the mod

### ISSUE THREAD

**Issue by Crunchmeister1** [roblenvic/Bonanza-Turbo#8]
The new changes made to the sim now cause the plane to float almost indefinitely on landings.

Also, it's now impossible to do a short field take off (1st notch of flap, apply full power while holding brakes) because it causes the plane to pop a wheelie in place.

**Comment by roblenvic** [comment]
Hi There,

I'm sorry to hear that. I am holding back on tweaking any more because
Asobo keeps changing things and each time requires hours and hours of work
to get things back to how they should be. To be frank I'm getting very fed
up with the way Asobo does this, often making things worse than they were
before. I will try to get the Bonanza back to how it should be when Asobo
leaves a bit more time before their constant tinkering with flight models.

Kind Regards,

Robert
